### ISSUE TITLE
Handle unknown clothing properly

### ISSUE THREAD

**Issue by emmamei** [emmamei/cdkey#1]
Clothing may be worn or unworn outside of the Key. The Key must be able to handle "rogue" clothing properly, removing it when putting on a new outfit.

**Comment by emmamei** [comment]
The current idea is to see where the clothing is located in inventory - the path - and to detach everything in this folder. Allowing the key to remove unknown clothing completely and totally is probably not worth the trouble - but a limited capability is most likely a benefit.

**Comment by silkymesmeriser** [comment]
The problem with a lot of stuff put om externally to the key is also that it may not be from #RLV in which case it wont show up properly in any of the @getinv or @getpath type commands.

I guess after stripping we could check if there were still layers or attach points being used and if so begin resorting to old school @detach:attachpt=force and @remoutfit:part=force the former would need some kind of whitelist to try and avoid removing things we really shouldn't like don't do an @detach:skull=force as that is usually hair.

**Comment by emmamei** [comment]
Had thought to find a path to some article of clothing, and detach everything in that folder - seeing as everything in the folder might be part of an outfit. Problem with removing things willy-nilly is you might remove something needed - for example, feet and/or feet alpha, or rings, or restraints... one has to be careful.

**Comment by silkymesmeriser** [comment]
That's true, we could perhaps support more of those special items using the ~folder idea, for now what I have set up it will remove other outfits that exist in the defined outfitsFolder it will also remove anything which is somewhere in RLV that uses the jacket, shirt, pants, undershirt, underpants or skirt but it does not search on the socks or shoes layer which should stop it accidentally finding feet though that and it also doesn't go for attachment only sets which should miss cuffs.

The downside of this of course is that it won't pick up on stuff that is outside the #RLV folder but there is not much that can be done with that without a strong chance of hitting things we shouldn't.

**Comment by emmamei** [comment]
It wont be possible to fix things completely as the removal of other items is likely to pick up things we want to keep on - including hair for one.

This is one situation where we'll have to let the "problem" go and let the user recover from it themselves.
