### ISSUE TITLE
URLs are hardcoded in code

### ISSUE THREAD

**Issue by emmamei** [emmamei/cdkey#100]
URLs are all hardcoded, including references to `api.silkytech.com`, `communitydolls.com`, and `cdkeyserver.silkytech.com`. Ideally, all such URLs should be set in some sort of system preferences file and read in. This might also save space in the code as well.

URL settings should also include all paths - these should be settable as well.

**Comment by emmamei** [comment]
Is this done?

**Comment by silkymesmeriser** [comment]
Partially it has been done for services as they had the memory to burn for now, however as for the rest they currently do not and the saving of removing the short URL strings will be less than the new code to read them from data files.

As such I think the rest should be added to a general code cleanup project to be handled after the beta release, but to be completed before releasing a stable.

**Comment by emmamei** [comment]
The focus isn't really about saving memory, but more about not having to change the code if something moves from, say, `api.silkytech.com` to `mei.strangled.net` ...or whatever it might be. Same for the URL paths.

**Comment by emmamei** [comment]
Here is the current list:

```
Dress.lsl:string outfits_url = "http://communitydolls.com/outfits.htm";
ServiceRequester.lsl:        while ((requestID = (llHTTPRequest("http://api.silkytech.com/name2key/add", HTTP_OPTIONS + [ "POST", HTTP_MIMETYPE,
ServiceRequester.lsl:        else URL += "http://";
ServiceRequester.lsl:            while ((requestID = (llHTTPRequest("http://api.silkytech.com/name2key/add", HTTP_OPTIONS + [ "POST", HTTP_MIMETYPE,
include/GlobalDefines.lsl:#define WEB_DOMAIN "http://communitydolls.com/"
```

**Comment by emmamei** [comment]
The URL base has been moved to `include/GlobalDefines.lsl`:

```
#define WEB_DOMAN "http://communitydolls.com/"
```

This is not just the domain but the actual base URL.

Closing ticket.
