### ISSUE TITLE
Making Dolly Outfitable does not present Dress button

### ISSUE THREAD

**Issue by emmamei** [emmamei/cdkey#105]
When one goes into the `Options` menu and selects `Outfitable` - going from disallowed to allowed - no change is made to the menu, and no `Dress` button is available. In any case, the `Dress` button should be available to the Dolly no matter what, right?

**Comment by silkymesmeriser** [comment]
Unless they are wear locked due to a recent change of outfit or they are prohibited from self dressing.  Either way the outfittable option does not affect doll.

**Comment by emmamei** [comment]
The thing here is that `Outfitable` sounds like the Dolly can be outfit by everyone, including herself - whereas it is in fact only making the Dolly outfitable by others.
