### ISSUE TITLE
Dress Menu Timeout makes it impossible to read entire menu

### ISSUE THREAD

**Issue by emmamei** [emmamei/cdkey#107]
With all of the items in my `Dress` menu the timeout for the menu seems to expire and the user ignored thereafter.

**Comment by silkymesmeriser** [comment]
Timeout increased to 60 seconds from last response.

**Comment by emmamei** [comment]
Was wondering if it could be made to be say 300s from last menu display (pages included) or whatever timeout is appropriate.
