### ISSUE TITLE
Posing by Dolly seems to trigger some sort of RLV initialization

### ISSUE THREAD

**Issue by emmamei** [emmamei/cdkey#108]
```
[01:42] Dolly Mei's Key: Mei めい (maystone) is looking at your poses menu.
[01:43] Dolly Mei's Key: Enabling RLV mode
[01:43] Dolly Mei's Key: Entered Vermont Maple rating is adult
[01:43] Dolly Mei's Key: @findfolder:> Outfits=134520352
```

Why is the Key initializing RLV when it should already be set - and why does it think I entered Vermont Maple when I've not moved for an hour or more?

**Comment by silkymesmeriser** [comment]
The initializeRLV function is reused for handling core restrictions post restart that's what the refresh parameter is for, in your case however it seems that RLVstarted wasn't set to 1 as for why that is the case is unclear.

**Comment by emmamei** [comment]
Aha... so in this case, it would appear that RLV was not set (though my memory doesnt recall for sure) and this activated RLV?

Will leave this open just in case...

**Comment by silkymesmeriser** [comment]
Sounds like yeah the final stage of RLV init seems to have not occured

**Comment by emmamei** [comment]
Is this perhaps related to bug #158 ?

**Comment by emmamei** [comment]
This doesn't seem to have happened since. Closing.
