### ISSUE TITLE
Enhancements to the Emergency Winder

### ISSUE THREAD

**Issue by emmamei** [emmamei/cdkey#109]
There are a few enhancements that can be done that might be nice. One is that the Emergency Winder can be explained in RP as a "key enhancement option" - specifically, some Keys might have it and some not... with the appropriate availability to the dolly.

The time before the Emergency Winder is available can also be made adjustable (in the same basic way that the Winding TImes are).

**Comment by silkymesmeriser** [comment]
Agreed but an enhancement not a bug, allocating to future.

**Comment by emmamei** [comment]
Making the wind time of the emergency winder seems to be of little use or desire, most likely. However, the ability to remove the emergency winder would very probably be of interest. It's also simpler to code.

**Comment by emmamei** [comment]
The specific enhancements listed here are not going to be implemented.
