### ISSUE TITLE
Lock new outfits against dolly changes for a period of time

### ISSUE THREAD

**Issue by emmamei** [emmamei/cdkey#11]
If a user changes dolly's outfit, dolly shouldn't change it right away. If dolly changes their outfit, let them change it at will.

**Comment by silkymesmeriser** [comment]
We could maybe make the time for this an option I was thinking of doing that with the poses once we get them working again perhaps do that first then will give an example we can use here too.

**Comment by emmamei** [comment]
Poses - at least according to original design - had that. A normal pose was time-locked (or was supposed to be) for 5 minutes, except for a Display Dolly, which was locked in a pose until the Doll Type changed.

**Comment by emmamei** [comment]
This might be simple to add - or not. Specifically put, a dolly would not be able to change an outfit chosen by someone else for a period of time (5 minutes? 10?). The user would be able to change at will. The dolly, if choosing outfits, could also change at will.

The thought is that when a user selects an outfit, the dolly has no business telling the user what the dolly will wear.

**Comment by silkymesmeriser** [comment]
I just hacked together a quick attempt at this using the same basic format I used to prevent the doll redressing after being stripped unfortunately I have nobody to test it with at the moment so will leave this open for now until it gets committed and either I or you can verify that it is working properly.

**Comment by silkymesmeriser** [comment]
I have just pushed a big commit with this in

**Comment by silkymesmeriser** [comment]
I don't like my current implementation on this there have been a few issues with it and I plan to redo it the new way I am thinking of would be more favorable to the dressing system in general too.

I am thinking of going instead for something like this:
@unsharedwear=n,unshareunwear=n - Locking out anything outside #RLV
@attachallthis:=n,detachallthis:=n - Locks out everything from the root of #RLV down.

But then if dress needs to make changes before the time is up then it can just make the command like this:
@detachallthis_except:<foldername>=add,detachallthis:<foldername>=force,detachallthis_except:<foldername>=rem
