### ISSUE TITLE
Developer Keys are locked in Normal Mode

### ISSUE THREAD

**Issue by emmamei** [emmamei/cdkey#111]
A normal key should still allow the developer to detach the key, or to open scripts and compile. It does not.

**Comment by silkymesmeriser** [comment]
Fixed just need to be the creator of Main

**Comment by emmamei** [comment]
Excellent. We discussed this, and the option of having Developers hardcoded in was not appealing and is a bad idea generally. This way it can be adjusted cleanly and any developer at all can be adopted.
