### ISSUE TITLE
setWindTimes needs checking to make sure it will not permit over 11 options

### ISSUE THREAD

**Issue by silkymesmeriser** [emmamei/cdkey#114]
Only 11 slots are available for wind times as the 12th is the main menu button, setWindTimes must verify that no more are permitted or a script error will result.

Test and fix if required.

**Comment by silkymesmeriser** [comment]
Tested, issue confirmed and fixed.

**Comment by emmamei** [comment]
This has to do with the ability of the user to set Wind Times to whatever they want; with this bug fixed, the menu will never overflow with more than 11 entries. How are entries chosen from the user's input?

**Comment by silkymesmeriser** [comment]
After the UI enhancement with the wind full buttons which also be extension means that the presented wind times are automatically adjusted for changes in key limit the entries are chosen as follows:

Upon user input first impossible values are filtered out.
- Any value which fails to cast to a valid integer.
- Values <= 0
- Values > 240
  The first two make no sense and the third would never be used due to the way the limits.

If after filtering out the impossible values we still have more than 11 values then they are reduced by this:

integer l = llGetListLength(windTimes); i = -(l/2);
while (l > 11) llDeleteSubList(llListSort(windTimes,1,--l&1),++i,i);

Basically doing it this way rather than using a fixed skip I went for as when it is less than n*2 this will tend to favour taking from the middle rather than the ends but in doing so makes it a sparse middle rather than simply pulling a chunk out of the range trying to be as faithful to the range of options entered by the user as possible when it's unlikely to be nice even divisors.

That list is then used for generating the menu where it follows the rules described in my commit message earlier.
Essentially
- Start with the lowest value
- While value is less than keyLimit - timeLeftOnKey and value is less than keyLimit / 2 add button.
- Then upon passing keyLimit - timeLeftOnKey if there is at least one more option in the list that is larger and less than keyLimit / 2 then add "Wind Full"
- Remaining values are not discarded however they will not be shown in the menu due to being irrelevant and misleading.
