### ISSUE TITLE
/75 xstats does not report correct wind time

### ISSUE THREAD

**Issue by emmamei** [emmamei/cdkey#115]
The report from xstats does not report the correct wind time, nor does it handle multiple Wind Times: it appears to be stuck at 30 minutes.

**Comment by emmamei** [comment]
This seems to be fixed; the complete range is reported.

**Comment by silkymesmeriser** [comment]
Closing

**Comment by emmamei** [comment]
The wind times output is still a mess; one of the last outputs had `Wind Full` listed in it, and some odd times.

**Comment by emmamei** [comment]
The problem with wind times seems to be resolved; other problems exist with stats but they are different.
