### ISSUE TITLE
Updating git to completeness

### ISSUE THREAD

**Issue by emmamei** [emmamei/cdkey#117]
Someone with the git repository should be able to create a Key from it. There are gaps in this at the moment, including password files, update scripts, and poses.

**Comment by silkymesmeriser** [comment]
Someone needs to go learn to make poses or come up with thousands of L$ to pay one of the few animators that will even discuss providing actual animation files outside of SL if you want to go that way.

Password files are separate for good reason they need to be kept out and not tracked but also for this same reason is why the one we have consists of only one single line.

Update scripts depend on the choice of distribution method of the distributor, granted I would like to get to fixing and properly testing an in world object distribution system it is also in many ways a project in it's own right and really I would almost be inclined to suggest that such a project should maybe have it's own repository even.

**Comment by emmamei** [comment]
None of this answers the post: someone should be able to create a Key from the git repo. In the case of poses, if they are truly full perm, they can be added to git.

In the case of passwords, the need for the files needs to be documented in code, with the proper definitions defined and the source for the proper entries explained.

**Comment by silkymesmeriser** [comment]
No they can't be added to git Mei they can't be saved from SL unless you are the creator

**Comment by emmamei** [comment]
Aha! Well then, the next best thing is to document all of it. I can take care of that.

**Comment by emmamei** [comment]
This is being done slowly. Documentation is being built up. Closing ticket.
