### ISSUE TITLE
Avi can get stuck with apparently bad carrying coordinates

### ISSUE THREAD

**Issue by emmamei** [emmamei/cdkey#120]
The carrrying code appears to activate randomly, and turning RLV on and off does not matter. The carrying point appears to be random, and stays within a Region. A relog does not make a difference.

Going offline and resetting scripts cuts the apparent carry and operation returns to normal.

**Comment by silkymesmeriser** [comment]
Should now be working

**Comment by emmamei** [comment]
Haven't seen this since I started using the Key again. Closing.
