### ISSUE TITLE
Wear lock activated and timer is set but no countdown and no RLV

### ISSUE THREAD

**Issue by silkymesmeriser** [emmamei/cdkey#128]
The wear lock function is currently behaving very strangely the variable wearLock is being set indicating that it is indeed active and the the wearLockExpire variable is correctly initialized to 600.0 ready to begin the countdown however that is where the good news ends because the timer never begins to count down and the 4 RLV restrictions that should be set remain unset.

**Comment by silkymesmeriser** [comment]
Status on this bug is presently unknown not direct move has been made to tackle it but substantial fixes in related functionality has taken place, in Main with the timers and in Avatar with the RLV/MoveLock/Carry/Collapse/Animation work.  This one should be tested needs us both to try it for now marking as needsinfo.

**Comment by emmamei** [comment]
For the Dolly, any normal clothing changes are _not_ locked - only those put on by others are locked. Thus, testing for proper wearLock activation now requires a second party, as the changes by Dolly are properly handled (i.e., not locked). This also needs to be documented.

The menu item should not disappear but show message that clothing is locked on: the initial code for this is in place, and will be finished shortly.

**Comment by emmamei** [comment]
This is being tested as part of issue #202
