### ISSUE TITLE
Transform: Redundancy: stateName vs currentState vs dollType

### ISSUE THREAD

**Issue by silkymesmeriser** [emmamei/cdkey#129]
Is it possible to get Transform to fully and correctly startup honoring the saved values for showPhrases if they are enabled without the redundant storage of stateName and currentstate when we have the dollType variable that can be made use of if we need to here?

Could you also look at add the option that you were asking for with Dressing at startup?

**Comment by emmamei** [comment]
`stateName` and `currentState` are extensively used; `dollType` is basically equivalent to `stateName`. `currentState` appears to be purely internal.

Both `stateName` and `dollType` (not a variable) are sent out using `lmSendConfig`, and both to the same value. However, the reaction to a 300 Link Message is different.

One problem originally addressed by early keys is if the "state" didn't match the "state name" and thus the differing variables. Doll Type `Regular` comes to mind, but that may be a bad example: there were others; don't know if any of it is relevant now.

**Comment by silkymesmeriser** [comment]
Maybe we could do something similar to the messages for wind times when they come in from user inputs they go to a handler in Main called `setWindTimes` as a link 305 internal command there they get processed and relayed to scripts using a link 300 as `windTimes`.

Maybe we need a `setDollType` handler on link 305 it could then even store it in a temporary variable and verify it against the current doll type by sending a link 303 for `dollType`.  Link 303 is a new link message that came in with the local database a query in effect that causes the variables named in the vertical bar | seperated list only to be replayed as link 300's.

**Comment by emmamei** [comment]
This has been resolved.
