### ISSUE TITLE
Develop and add back poses

### ISSUE THREAD

**Issue by emmamei** [emmamei/cdkey#13]
Poses were removed in order to gain back memory in Main.lsl. Use the new Poses.lsl script and build it so it handles all posing.

**Comment by emmamei** [comment]
This is a major capability of the key and needs to be added back before a release occurs. The poses should be locked for 5 minutes, unless the Doll is a Display Dolly, in which case the pose is locked permanently until the Doll changes type or another pose is chosen.

**Comment by emmamei** [comment]
This could be seen as an enhancement, but in truth this is a major feature that was stripped at one point and needs to be restored.

**Comment by emmamei** [comment]
This is important and will block the release of the Key until done.

**Comment by silkymesmeriser** [comment]
I've had a go at this in my latest commit, you will also notice that I have organised the repository some putting the unpreprocessed files and includes in their own folders etc.

**Comment by silkymesmeriser** [comment]
A few notes about my implementation that as best I can tell were not in the initial version but might have been.

Not only does the pose have a timer (if not a Display type) it also will not let the doll unpose or change pose if they were posed by anyone but themselves.

If they are not currently in a pose then they may pose themselves if they do pose themselves they can unpose at least until someone else poses them.

**Comment by emmamei** [comment]
Perfect. I had a go at the Preprocessor and it mangled things badly - dont know why.
