### ISSUE TITLE
After using emergency winder, Key still shows sign of collapse

### ISSUE THREAD

**Issue by emmamei** [emmamei/cdkey#130]
The Key will still have a hovertext of `Disabled Dolly!` and the main menu will still say: `You need winding.` even though it has the correct number of minutes listed. After a few minutes, these items correct themselves.

**Comment by silkymesmeriser** [comment]
Commit 79aeb4e0cfcda5be21f21a3cd52f31d9cf2645b7 should fix this as it now triggers the timer event to fire the next sim frame after the collapse state changes.
