### ISSUE TITLE
Meta: Variable modernization and renaming project

### ISSUE THREAD

**Issue by silkymesmeriser** [emmamei/cdkey#138]
I have crated this issue with the intention of us using it as a meta issue to track the state of any and all variables which are being renamed or redefined in the key, this is a potential place where things could go wrong or where interim bits of transitional code could get forgotten lets makes sure we track it properly.

At minimum I think we should try and make sure to link an issue back here for every affected variable.

**Comment by emmamei** [comment]
This seems a very broad report and not necessary. Also how does one "modernize" a variable anyway? And a _Project_ to rename variables? I don't see where it is needed: update the variables as you go.

**Comment by silkymesmeriser** [comment]
And then you have to deal with the fact you have two copies of the same thing floating around under different names possibly with different values which leads to interim code being needed until the depreciated variable is entirely eliminated such things should be tracked as open issues until the interim code is removed.  Not tracking such things helps to create situations where obsolete code hangs around acting in the best case as a source of increased script time and memory consumption in the worst case forgotten code becomes bugs waiting to happen, have tried to make sure that as far as possible the only things dealing with the obsolete forms of the variables is all in one file and well commented as to it's nature as a) Interim code and b) Clarifying exactly why it is there, what it's purpose is etc for most things it amounts to a simple one or two line conditional in the handler for whichever of the two (New/Old) will arrive last where both exist.  Things are more complex when dealing with such as list parsers etc of course.

**Comment by emmamei** [comment]
What this issue is asking for or suggesting is unclear - and which variables need "modernizing" and such is unknown. Closing.
