### ISSUE TITLE
Key gets stuck cycling between two animations

### ISSUE THREAD

**Issue by silkymesmeriser** [emmamei/cdkey#139]
The keys animation refresh code can on some pose change events enter a state in which it has one named animation actively set as it's animation to trigger in keyAnimation while still holding the proceeding animation's UUID as the key to check for in llGetAnimationList.  This results in a rapid cycling up of the refresh rate to the hard limit resulting in the animation being stopped and restarted constantly at several Hz this should never occur.

It is likely that there is needed an enforced setting of the keyAnimationID to NULL_KEY in any case where keyAnimation is changed from non empty to non empty to force the key to redetermine the UUID of the playing animation and thus get the correct value.

**Comment by emmamei** [comment]
This appears to be fixed.
