### ISSUE TITLE
Develop and refactor collapsing into a standalone script

### ISSUE THREAD

**Issue by emmamei** [emmamei/cdkey#14]
Develop the Collapse.lsl script to free up space in Main.lsl and to segregate the code appropriately.

**Comment by emmamei** [comment]
This is most likely a low priority item - but when it comes to it, it would be nice and would free up more space in Main.lsl.

**Comment by silkymesmeriser** [comment]
I'd take a look at my new code when I commit it later before going that route, the majority of the collapsing code is now handled by RLV.lsl the animation part of it is still in Main.lsl but has been rewritten to be non blocking too.

**Comment by emmamei** [comment]
Good enough.
