### ISSUE TITLE
Timers activate at wrong time and have competing link messages

### ISSUE THREAD

**Issue by emmamei** [emmamei/cdkey#146]
The various expire timers need an overhaul. There are points in the code where they appear to be an absolute time relative to script start, and other times they appear to be a measured time span.

All code is in `Main.lsl`.

**Comment by emmamei** [comment]
This may be related to issue #128.

**Comment by silkymesmeriser** [comment]
Except #128 is fixed now.

**Comment by emmamei** [comment]
This appears to be quite irrelevant to #150. In any case, this seems to be a case of understanding and documenting which is which. Will check each time limit individually for proper functioning.
