### ISSUE TITLE
Restore one-way settings

### ISSUE THREAD

**Issue by emmamei** [emmamei/cdkey#15]
Some settings are supposed to be one-way: the wearer can set them - but not unset. Restore this capability to the key.

**Comment by emmamei** [comment]
This actually seems to be not a problem; the code layout was misleading - but the code is like this:

```
    // One-way option
    if (detachable) pluslist += "no detaching";
    else if (controller) pluslist += "detachable";
```

Only the controller gets the _detachable_ setting, for the wearer this is a one-way option.

**Comment by silkymesmeriser** [comment]
Yeah I did it that way to reduce the redundancy of having a whole series of options being coded twice one for each menu.
