### ISSUE TITLE
collapseTime goes below zero

### ISSUE THREAD

**Issue by emmamei** [emmamei/cdkey#152]
`collapseTime` goes under zero - this is an invalid value and needs to be rectified.

**Comment by silkymesmeriser** [comment]
Actually it's correct, collapseTime is negative since future times are positive, T+x to obtain a past time one subtracts time.

**Comment by emmamei** [comment]
Can't be right. Link messages show a value of less than -1400 on `collapseTime` - which, given the testing for `collapseTime != 0` means that the Doll will be seen as collapsed even though the collapse time got passed long ago. Link Messages have time spans, even if the code uses actual time.

**Comment by silkymesmeriser** [comment]
It's set to 0 when it isn't relevant like all the times, if you invert it you will break the TP home and emergency wind menu options so they never show.

**Comment by emmamei** [comment]
This "bug" is a red herring; the "fixes" were reverted in local git and testing will continue....
