### ISSUE TITLE
Improving the way we handle data

### ISSUE THREAD

**Issue by silkymesmeriser** [emmamei/cdkey#155]
As mentioned in the other post we know that there are a number of reasons why it makes sense to resolve much of the complexity in how we are handling data and working on simplifying and unifying that.  I have already given some thoughts to a lot of points in this area as a result of the discussions that have led to developing this line of thinking.  There are different facets to this and I'd really like to be more coherent and organised about this as that alone is going to help go a long way to eliminating and avoiding inconsistencies etc.

I want to break things down as it may be some parts being lower priority we decide to defer others prioritize and perhaps some things will show up to be redundant and end up being dropped and it is easier to focus on one thing at a time.

**Comment by emmamei** [comment]
This suggestion sounds good but is vague.... closing - if specific suggestions come up, they can be opened in their own tickets or this one reopened.
