### ISSUE TITLE
Comments should be completely ignored

### ISSUE THREAD

**Issue by emmamei** [emmamei/cdkey#16]
Add code to completely and totally ignore comment lines (lines that start with '#').

There should be no way any comment can be read or analyzed or used - no matter what's contained in it.

**Comment by silkymesmeriser** [comment]
Try using this

```
dataserver(key query_id, string data) {
    list validConfig = [ "wind time", "max time", "doll type", "helpless dolly", "controller", "auto tp",
                         "can fly", "outfitable", "pleasure doll", "detachable", "barefeet path", 
                         "user startup rlv", "user collapse rlv", "user restore rlv", "quiet key" ];

    if (query_id == ncPrefsKey) {
        if (data == EOF) {
            doneConfiguration();
        } else {
            if (data != "" && llGetSubString(data, 0, 0) != "#") {
                integer index = llSubStringIndex(data, "=");
                string name = llGetSubString(data, 0, index - 1);
                string value = llGetSubString(data, index + 1, -1);
                name = llStringTrim(llToLower(name), STRING_TRIM);
                value = llStringTrim(value, STRING_TRIM);
                list parameterList = llParseString2List(value, [ "|" ], []);
                string param = ZWSP + llDumpList2String(parameterList, ZWSP);
                if (llListFindList(validConfig, [ name ]) != -1)
                    llMessageLinked(LINK_SET, 101, name + param, NULL_KEY);
                //--------------------------------------------------------------------------
                // Disabled for future use, allows for extention scripts to add support for
                // their own peferences by using names starting with the prefix 'ext'. These
                // are sent with a different link code to prevent clashes with built in names
                //--------------------------------------------------------------------------
                //else if (llGetSubString(name, 0, 2) == "ext")
                //    llMessageLinked(LINK_SET, 201, name + param, NULL_KEY);
                else
                    ownerMsg(WARN, "Unknown configuration value: " + name + " on line " + (string)(ncLine + 1));
            }
            ncPrefsKey = llGetNotecardLine(ncName, ++ncLine);
        }
    }
}
```

The code above is what I've got running at the moment it actually does several validations before it even send the message across the link.
- Exit notecard reading phase if reading EOF
- Then filter and ignore any blank or comment lines
- Then check lines for core scripts are one of the valid config directives (From the list validConfig)
- FUTURE: Commented section adds support for extension configuration values for addons or modules
- If all else fails do not send on link and print a warning

You might need to cut that validConfig list down a bit to get it to work correctly for the older version.

**Comment by silkymesmeriser** [comment]
The above is already in the one I'm stabilizing to commit back again hopefully tomorrow so I'll grab this issue to cover it with that.

**Comment by emmamei** [comment]
Good to hear it. Thanks!

**Comment by emmamei** [comment]
The configuration is actually "read" by Start.lsl - and ignores comments right up front before analyzing the line for valid entries. The link message is read by Main.lsl and RLV.lsl for further processing.

The code you gave also will not work in the current code as the function doneConfiguration() is missing.

**Comment by silkymesmeriser** [comment]
I'll have a commit with it later today hopefully as I think I managed to squash the bug in the new follow code.
