### ISSUE TITLE
Key takes emotes away but doesn't restore

### ISSUE THREAD

**Issue by emmamei** [emmamei/cdkey#18]
The Key takes away emotes for a down dolly, but in the current case doesn't seem to restore them.

emotes should only be taken if the dolly collapses - and restored on restore from collapse.

**Comment by emmamei** [comment]
Is this fixed?

**Comment by silkymesmeriser** [comment]
Should be yes, collapsing now reuses the same RLV restriction code as AFK mode and toggling that on and off does not leave anything.

Of course the new state tracking code means that everything should get taken out for either of those as they use a virtual script name in the tracking code which is then @cleared to restore.  Doing it that way has the further advantage that the added userbase and usercollapse restrictions can't be used to evade default ones.
