### ISSUE TITLE
Debug the "New Owner" process

### ISSUE THREAD

**Issue by emmamei** [emmamei/cdkey#20]
Handing a key to a new user should be clean and flawless. The Preferences note card should be reset or deleted; the listeners reset; and the outfits reread - and whatever else is appropriate.

**Comment by silkymesmeriser** [comment]
As far as I'm aware the code I am working on getting uploaded today should do this Start.lsl handles removing the old preferences notecard and then initiates a full reset of all scripts.

The key also now contains an additional notecard PreferencesExample to serve as documentation of the Preferences notecard format even after the other Preferences notecard is deleted.  Transform.lsl has been adjusted accordingly and now ignores any notecard whos name begins with the word Preferences.
