### ISSUE TITLE
Documentation should be available from the Key itself

### ISSUE THREAD

**Issue by emmamei** [emmamei/cdkey#23]
Given the style of release of the Key, and the desirability of being able to transfer and move keys about at a moment's notice, it is worth it to have the Key present a Help Notecard when selected from the Main Menu.

**Comment by emmamei** [comment]
This has just been added to the Key - the initial help file is present. The capability needs testing.

**Comment by silkymesmeriser** [comment]
It works fine though I just upgraded it to an actual little help menu so far the options are as follows:

Help Notecard, Join Group, Visit CD Room
Report Bug, Ask Question, Suggestions

The bottom three are actually synonyms they all point to https://github.com/emmamei/cdkey/issues/

**Comment by emmamei** [comment]
I'd change to the following:

Help, Join Group, Landmark

These are commonly used and widely known - and the last three are debatable: most people would just be confused by them - or by GitHub.

**Comment by emmamei** [comment]
This capability is done - and documentation is being written.
