### ISSUE TITLE
nofly RLV restriction set on startup

### ISSUE THREAD

**Issue by emmamei** [emmamei/cdkey#26]
This RLV restriction is not part of the configuration file, and is set every time the Key starts up.

It was originally thought to be part of the Helpless Dolly setting - or to be set by the configuration file. Neither appears to be the case.

**Comment by silkymesmeriser** [comment]
Already fixed in my local version by adding it to the preferences notecard will be doing a commit shortly has been delayed a bit as I ran into a memory issue with Main.lsl trying to fix another bug but it's looking good now thanks to the new script.
