### ISSUE TITLE
Doll can become stuck in AFK mode

### ISSUE THREAD

**Issue by silkymesmeriser** [emmamei/cdkey#27]
It is currently possible for the doll to become stuck in AFK mode, the automatic AFK mode setting can be activated even when the doll does not have access to the menu option to reverse it.

**Comment by emmamei** [comment]
I can see where this would happen. The Key automatically enters AFK when the user status becomes "Away". If there is no option for the Doll to switch out of AFK, then this could be a problem.

Solution is to allow the Key to automatically come out of AFK if it entered automatically.

**Comment by emmamei** [comment]
Just committed code to solve this problem: added variable, autoAFK, which is set when wearer enters AFK automatically - and it allows the Key to exit AFK automatically as well. For robustness, autoAFK is set and reset if AFK is selected manually one way or the other.
