### ISSUE TITLE
Mistress Key is misused in code and misunderstood

### ISSUE THREAD

**Issue by emmamei** [emmamei/cdkey#31]
The code uses "Christina Halpin" (the Key Creator) as a sort of default Mistress Key - and should not.

This leads to an erroneous reporting of Christina Halpin when the Mistress should be reported as none - and also leads possibly to an error in reporting when the Mistress _is_ Christina Halpin.

**Comment by silkymesmeriser** [comment]
I've noticed initially I was trying to follow the original on that but I see no reason why it should be that way and it also creates the need for the unnecessary hasController variable so I am working towards setting it up in the way I would consider correct.

Namely no controller should set MistressID to NULL_KEY then if we need to know if the key has a controller we can simply test if (Mistress ID != NULL_KEY)

**Comment by emmamei** [comment]
I agree. I suspect the reason was probably to allow Christina to help any dolly that called for help with access for her to TP and so on; this should be taken care of with the list of exceptions I'd say.

Might conserve space to use hasController but can be limited to places like the menu where it is used often - and one can simply use:

```
integer hasController = (MistressID != NULL_KEY);
```

**Comment by silkymesmeriser** [comment]
Right, actually what I have done at the moment is use

#define hasController (MistressID != NULL_KEY)

It's in the GlobalDefines.lsl which is #include into each script, one of the other nice things about using the preprocessor now things like formatFloat(), memReport() and other functions used in multiple scripts come from an include so if we ever change the function we do so in just one place.  Tends to help reduce bugs from updating something in one place and forgetting to do so elsewhere too.

**Comment by emmamei** [comment]
Using the preprocessor is a good idea but hides inefficiencies too - using `hasController` as an integer (time involved: variable fetch) has to be faster than the `Mistress_ID != NULL_KEY` which involves two variable fetches and a non-boolean comparison.

**Comment by silkymesmeriser** [comment]
In this instance though `NULL_KEY` is not a variable it's a constant which means that at least assuming that the LSL compiler is like any other compiler the built in constant is replaced with it's value at compile time not runtime.  As for the boolean comparison considering that LSL doesn't have any speedup doing bitwise comparison over integer comparison and lacks a bool type I suspect it makes little difference in this case.

With LSL also we tend to be running into much more issues with memory than with script time.

**Comment by emmamei** [comment]
Well consider this then:

```
hasController
```

One integer variable of size _x_.

```
Mistress_ID != NULL_KEY
```

Two keys of size _y_ and a comparison of size _z_ - much bigger than a simple integer variable.

Also, if `NULL_KEY` is a constant and it is replaced with the integer and all - why remove all instances of `TRUE` and `FALSE`?

**Comment by silkymesmeriser** [comment]
NULL_KEY is not an integer it's a 36 byte string, the key type in LSL is basically a string even if it needs a cast to combine it with other strings.  You can verify this with llMessageLinked and two scripts send a message like follows:

llMessageLinked(LINK_THIS, 0, "", (key)("This is some arbitrary text cast to key type"));

Verify using a link_message event in a second script in the prim that taking the key value casting it back to a string returns the original string by passing it to llOwnerSay or similar.

TRUE & FALSE like all integer constants in LSL are 6 bytes not 4.  Plus they use more characters which at the time was an issue.

**Comment by emmamei** [comment]
That doesn't speak to the fact that

```
hasController
```

(an integer of size _x_) takes up less space than

```
Mistress_ID != NULL_KEY
```

that is, two keys of size _a_ and _b_ plus a comparison _c_ ... or,

x < a+b+c

**Comment by silkymesmeriser** [comment]
True, presuming that both would be somehow removed from memory by using the integer method but as LSL has no alternative storage other than memory for us to move the actual key data to that doesn't really work.

That said the new code takes advantage of the fact that we were already doing list comparison to determine if a user was a controller or not in order to support several additional builtin controllers, now it can handle multiple users controllers also though limited to a max of 12 to stop it growing to use unlimited memory.

As such it's more a question of whether llGetListLength(MistressList) != 0
