### ISSUE TITLE
llMessageLinked and LINK_SET

### ISSUE THREAD

**Issue by emmamei** [emmamei/cdkey#32]
Nearly all calls to `llMessageLinked` use the setting `LINK_SET`. This sends the message from `llMessageLinked` to all prims. However, using `LINK_THIS` the way Transform.lsl does might be more advantageous, as it does not need to propogate the messages everywhere. `LINK_THIS` only sends messages to the prim that the script is in.

**Comment by silkymesmeriser** [comment]
This would only make an actual difference if we had scripts in prims other than the root that would be excluded from receiving the message by doing this and in our case we do not.

I did briefly consider the idea of actually moving the scripts to different prims so we could target them using link numbers as addresses but to be honest I am unsure there is really a need, during the heaviest burst link activity the key ever has (An initial clean startup requiring a read of prefs) the script time peaks at about 40 microseconds and that's including the CPU used for the recompile itself.

I guess it wouldn't kill us to change it I am just doubting we will notice any effect.

**Comment by emmamei** [comment]
Guess I am confused as to what it means. There are scripts in my hair, my feet, and often in other attachments for resizing and such - or in things like collars and cuffs. If you use `LINK_SET` it sounds like every last script on the avatar gets the `llMessageLinked` message.

I take it from what you've said that this is not the case.

**Comment by silkymesmeriser** [comment]
A linkset it an object it only goes to script within the same object

**Comment by emmamei** [comment]
This explains things better - no worries.
