### ISSUE TITLE
Multiple Controller Support

### ISSUE THREAD

**Issue by silkymesmeriser** [emmamei/cdkey#33]
I'm leaning towards the idea of putting in multi controller support for the key, the idea you suggested of using an exceptions list to let certain helpers have automatic controller access means doing an llListFindList type test for if someone is a controller anyway.

If we are going to do that especially with the way the key deals with controllers where they can only add or remove themselves means it's a simple case of making a list of controller ID's to add to the default list at runtime the implementation would not be a lot of work especially as we don't need to make a complex menu interface to handle it.

**Comment by emmamei** [comment]
I'd say if we can make it "easy" to implement - we should lay the groundwork and leave the actual implementation. We already have a bit of it with the Creator, the Master Winder, and two Developers as pseudo-controllers already.

I'd really like to have a Petite Key, Child Key, and Standard Key ready no later than the Japanese Doll Festival on 3 March - which means a feature freeze and weeks of testing before then.

**Comment by emmamei** [comment]
This appears to have been implemented.
