### ISSUE TITLE
Adjust Operation for Struggling Sims

### ISSUE THREAD

**Issue by silkymesmeriser** [emmamei/cdkey#34]
I was doing some experiments with script time usage and for one of them I tried setting up a small addition that will slow the timer rates and turn off a few non essential scripts normal running the key uses about 20 microseconds which for an item of this sort is not excessive by any means but by reducing the timer rates and by turning off 4 of the scripts unless the menu is in use namely Dress, MenuHandler, Taker and Transform that reduces by nearly a factor of 5 to around 4 microseconds.

It's significant enough that I'm considering possibly leaving it in set to trigger when the region time dilation drops (ie server side lag is getting really bad) in that regard would be similar to devices like MystiTool and others that try to be friendly on sims when they detect they are struggling.

Of course if I do leave it in there is the question of should we actually stop Transform or not as that stops phrases arguably that isn't going to kill anybody if the sim is so bad off it has a TD bellow a threshold like 0.92 or so.

**Comment by emmamei** [comment]
Not sure. It's yet another untested new feature - of which we have so many at the moment. We should focus on making a working key instead of one full of new features that don't all work right.

**Comment by silkymesmeriser** [comment]
I just had to do a commit with a redone startup process anyway due to a race condition between Dress, RLV & Transform I decided to leave it for you to take a look at for now but all the code for it is bracketed with a preprocessor define which will make it easy to remove if we decide against it.

**Comment by emmamei** [comment]
This appears to have been implemented.
