### ISSUE TITLE
Preferences changes: yes/on & no/off & "busy is away"

### ISSUE THREAD

**Issue by silkymesmeriser** [emmamei/cdkey#35]
Because I thought it would be more user friendly for some users I added 2 lines of code into Start.lsl where it processes the configuration to make the values "yes" or "on" equivalent to 1 and "no" or "off" equivalent to 0.  I suspect that actual words might gel better with some users than numbers and if we write them as such in the PreferencesExample I suspect there is a lot less chance of someone putting some completely off the wall number in there.  It seems obvious perhaps what the 1 and 0 mean but then we are both highly technical and used to speaking binary as we both code not all users would necessarily find it as obvious as we do.

The other thing I added was partly through a comment by a friend of mine another older SL user who reminded me that most of us older users tend to set our viewer to busy mode rather than away at least in part because the forced away anim is nearly universally hated.  As such I added the preference "busy is away" if this is set to true then the key will treat the user entering busy mode as if they had entered away mode.

**Comment by emmamei** [comment]
This isn't an issue exactly - and you've already done it. So asking me what I think is irrelevant.

In any case, I like both of these.
