### ISSUE TITLE
No one can touch Key when Wound Down

### ISSUE THREAD

**Issue by emmamei** [emmamei/cdkey#36]
Key wound down and no one could touch it to Wind the Dolly back up.

**Comment by silkymesmeriser** [comment]
I never did manage to verify this issue not sure if that is because it got fixed indirectly by something else or what, have you had any issues with this since?

**Comment by emmamei** [comment]
Haven't seen it - must have been LSL or something.

**Comment by silkymesmeriser** [comment]
Ok I'll go ahead and close this for now and can reopen if it recurrs.
