### ISSUE TITLE
Menu: Reducing code redundancy

### ISSUE THREAD

**Issue by silkymesmeriser** [emmamei/cdkey#45]
There is a lot of code redundancy in the menu handlers that could be reduced a lot of the options could be reduced there are several areas where this can be done and several implementation options are available to achieve it.

By far the majority of the code in MenuHandler is for handling a series of toggle options all of which are specified as individual items and are specified twice one for enabling and one for disabling the option, this is largely because of conflating data and code thus the code is being specified over and over again for different data while the code itself is basically the same.

Probably almost half the script is essentially identical code written over and over again for each different option name, this is one example of a good usage for lists which will be definition be static lists of options.  The biggest single example of this is the current options menu which as it stands currently amounts to a good 200 or so lines of code.

See comments for my proposed new implementation of this to go with the issue #42 work.

**Comment by emmamei** [comment]
This is a good idea for the next version of the Key.

**Comment by silkymesmeriser** [comment]
I propose that we firstly split the options menu into two parts once all the features are properly included in it with both buttons and handlers it would be more than 12 buttons anyway, I suggest that we should split the RLV options from the key options such that you would have options would become two sub menus along the following lines:

RLV Options: Auto TP, Can Fly, Can Sit, Can Stand, Helpless Dolly etc etc.
Key Options: Allow Takeover, Can AFK, Can Dress, Pleasure Doll etc etc.

You will note that yes the proposed key options many of them do in some way involve RLV type functionality (dressing, stripping etc) however there is a clear distinction that splits them into two categories, the first group are all tied directly to one or more persistent type RLV restrictions that are applied with immediate effect and remain so long as the option is in effect.  Additionally the RLV menu would be the place where any optional down collapsed dolly options would go, these could be examples of hypothetical two way RLV restriction options on the basis of the following.  When the dolly is wound they would be able to freely change said options in either direction but once they go down they would not be able to unset them until they are wound again is the one place I can see where making RLV restriction choice two way would not inherently defeat their own purpose.

The latter where RLV is involved it mostly involves one shot RLV commands ie command:option=force and where any persistent restriction is issued related to it the added restrictions are temporary and are applied at time of use not as an immediate and direct consequence of the option itself.

As for the implementation I believe all this can be done with a surprisingly small amount of code I am thinking along the lines of storing all the data needed to generate and handle these menus with one list and two integers.  Using a shorter subset of the full list to explain the idea I have in mind.

I am going to base this example on the following options including some which exist and a couple I am making up as there are no current examples that I can think of that would fall into the same menu and class in this case they are being added here solely as example usage and are not being proposed as additions at least not additions that would be included in this work.

Takeover - Key menu, unrestricted two way
Auto TP - RLV menu, restricted one way
No AFK - Key menu, restricted one way.
Can Dress - Key menu, unrestricted two way
Helpless - RLV menu, restricted one way
Hear Unwound - RLV menu, unrestricted two way (when wound) - hypothetical option would cause the dolly to be @recvchat_sec=n if collapsed.

list options = [ "Takeover", "Auto TP", "No AFK", "Can Dress", "Helpless", "Hear Unwound" ];
integer rlvOptions = 0x32;   // 50 ie 2 + 16 + 32
integer oneWay    = 0x16;   // 22 ie 2 + 4 + 16

The calculation for the integers being based on the sum of the following for the options it applies to:

1 << listIndex;

This way the menu generating function could follow through the list in a loop and using the following concept decide firstly if an option belongs in the menu that it is generating or not and secondly if it should be shown to a non controller user or not.

```
#define CHECKED ""
#define UNCHECKED ""
integer enabledOptions;

doOptionMenu(integer rlvMenu, key id) {
    integer index; list showButtons;
    for (index = 0; index < llGetListLength(options); index++) {
        if (RLV && ((rlvOptions & (1 << index)) != 0)) {
            if (enabledOptions & (1 << index)) == 0) {
                showButtons += [ UNCHECKED + llList2String(options, index) ];
            }
            else {
                if ((oneWay & (1 << index)) == 0) || ((isMistress(id) && (id != dollID))) {
                    showButtons += [ CHECKED + llList2String(options, index) ];
                }
            }
        }
    }
}
```

Or something along those lines maybe?

**Comment by emmamei** [comment]
I don't like the concept of the "RLV menu" - many people won't even know what RLV is - or what the restrictions are. I'd like to stick to functional divisions - perhaps a section specifically for downed dolly restrictions.

**Comment by silkymesmeriser** [comment]
I'm not really set in stone on the systematics of what to call the menu here we could perhaps call one "Abilities" and the other "Features" for example or whatever naming seems better the purpose of the split it that while we can page dialogs together to support more options that has it's downsides too the fact is paged menus exceeding 2 maybe 3 pages are a usability nightmare especially when trying to stick as much as possible to avoiding menu blocking/locking which means keeping as much as possible to a stateless design.  With the options menu however that would make doing something like reshowing the same page after picking an option to reduce mouse clicking through dialogs will be difficult with a paged menu.

The reason for that is a paged menu the exact page option x shows on depends on the count of enabled options for the menu user but any time they click a one way option they would change the count.  So for the options menu I would rather we did not use dynamic paging.  It's different using a dynamic pager with such as the poses menu or the doll types menu because while again buttons could become changed or reordered they would do so only when items are added and removed from the key's inventory not as a consequence of the use of the menu in and of itself.

I mean consider the dynamic options menu for a moment under the conditions where both the doll and one or more of their controllers were using the menu at the same time.  It's a positive thing about the key we can even support that but we do not want to end up with a situation where that means that the menu is going to be changing structure while it's being used!

**Comment by emmamei** [comment]
Is this completed?

**Comment by silkymesmeriser** [comment]
Not yet got moved to future as it is a fairly significant rewrite.

**Comment by emmamei** [comment]
This is either completed or irrelevant; it may be revisited in the future.
