### ISSUE TITLE
Pose fixes required for petite key viability

### ISSUE THREAD

**Issue by silkymesmeriser** [emmamei/cdkey#47]
If we are going to make a petite key truly viable we are going to need to do one of two things for the collapse anim at least.
- Get the anim made correctly to be compatible with petites.
- Implement a script hack around the above similar to the OC heightfix

**Comment by emmamei** [comment]
If we get a `collapsed` animation, then the rest can be foisted (unfairly) on the user. Assuming petite poses can be found and utilized, then they can be added as warranted.

**Comment by emmamei** [comment]
This is related to issue #536.

**Comment by emmamei** [comment]
Closing now as this feature will not be implemented now or in the near future.
