### ISSUE TITLE
New > folder handling

### ISSUE THREAD

**Issue by silkymesmeriser** [emmamei/cdkey#48]
I have changed the way that we are handling > folders.  Initially they were treated like outfits which was a disaster, then the move to ignoring them completely which locks out a lot of perfectly good outfits for many people the new handling however works differently.

Now there is a new class folder test isParentFolder(string f) when a folder is selected for which that function returns true rather than either ignoring or wearing it we instead append it to the activeFolder path and getinv again ie recurising into the tree.

I'll get it committed a little later after playing with it some more and double checking some of the more obvious potential pitfalls.  If any issues are found with this please add a reference back to this issue to keep them all together.

There is one point about this addition that does need to be considered, it's currently a known issue that the tracking for the menu with this is not going to work correctly with multiple simultaneous menu users inside the dress module.  There are solutions to this with some pros and cons to each and some need viability checking also.

As it stands I see several possible options:
- Implement a blocking menu that ensures that only one user browses outfits at a time, this is probably the "simple" solution but I am not that in favor of it given that currently everything else in the key actually handles multiple users quite effectively.
- Track activeFolder for several users at a time this would mean implementing something like a stride list in the form menuUserID, activeFolder probably with a timestamp to forget old users unless we just wipe the entire list when all go idle.
- Need to check viability on this but perhaps we don't need to do either of the above, maybe we can use RLV features to help us @findfolder: possibly though the caveat with that would come in if <selectedFolder> has a name which is not unique in the > Outfits/\* tree as a whole.

Course the limitations of LSL are absolutely showing through on this one, were it not for the memory limits and the lack of true arrays the solution would be fairly obvious as you could do things like cache the folder tree and spot any ambiguous names so that they could be disambiguate in some way.  Course doing so would need at the very least a proper multi-dimensional array to be remotely efficient.

**Comment by silkymesmeriser** [comment]
On second thoughts I just realized Dress.lsl kinda needs a blocking menu as it stands already, the ID of the next person to present the menu to is stored in a single var dresserID so effectively right now if one person is using the menu and another person clicks on the Dress button to enter the Dress module it overwrites that UUID field and the menus from then on will be spawning for the new user effectively killing the transaction in progress.

**Comment by emmamei** [comment]
Ouch. Didn't realize that multiple users weren't handled well.

**Comment by silkymesmeriser** [comment]
Yeah unfortunately I don't see a way to avoid it well not without some rune goldberg machine involving lists tracking not only where everyone is in the menu but the current script task being performed for them etc too.

I did some work on the listeners I found totally reducing them to just one didn't work well so now I have it set up that while they use the 5 different channels as and when needed they are only active when they are actually called and closed immediately on getting a reply.
