### ISSUE TITLE
Improvement discussion: HTTPdb

### ISSUE THREAD

**Issue by silkymesmeriser** [emmamei/cdkey#49]
I've managed to get to writing a basic implementation of a HTTPdb interface for the key which currently backs up and provides retrieval for most settings, some need implementation work such as recording the expiry times for things like pose timers etc as they will need to be converted from the script timestamp form they are stored into to an absolute value of seconds left.

Currently updates are preformed every 2 minutes but only for changed information most noteably timeLeftOnKey is reported with every update on average around 1.2kB total in+out is transferred per update which should be sustainable, concurrency for the entire grid currently averages around 60,000 which would only be around 600kB/s if every single online avatar was wearing a key and the dedicated server the api is hosted on never goes over ~9% load currently.

Security is currently implemented using a combination of features, firstly all requests that don't come from valid linden lab owned simulators are denied, secondly the X-Secondlife-Owner HTTP header added by the simulator itself is used to determine the record to be accessed or updated.  That alone should mean that short of a simulator compromise accessing another persons record should not be possible but an additional layer of protection is added with a salted SHA1 hash including a unix timestamp which has to be less than 60 seconds old to verify (replay protection).

Performance is significantly improved compared to notecard from request to retrieval with all processing time included from my own account which has 30 records in the database is completed in 0.7 - 0.8 seconds, notecard is approximately 200-250ms per line read.  Due to the performance benefit startup times are now reduced especially for script resets where they are now under 5 seconds provided there is no need to read the notecard (ie it has not changed).

**Comment by silkymesmeriser** [comment]
I should point out that it does remain optional and can be disabled either through the menu or by creating a notecard (well for that matter any inventory item) with the name .offline inside the key.

I am planning to implement an additional option before release that would work from the service end to not store data for all current or future keys belonging to an avatar while also actively purging any data which they may have already saved.  Stored data is also going to be purged if the user the user puts their key into offline mode and thus stops accessing the database, both to avoid storing data on users that do not want it and also to avoid the database becoming clogged with records for users who either no longer use secondlife or at least no longer use a supported key.

I'm debating where to set the timeout though to balance between the desire to not keep things longer than necessary and not wanting to purge records of people that do want to continue using it and are perhaps away from SL for whatever reason.  What do you think of 30 days?

**Comment by emmamei** [comment]
This is yet another brand new feature - and I'm not convinced it's a good one. OpenCollar had tremendous problems when their database went away, and we don't want Community Key owners to suffer the same fate. Making it optional doesn't solve that problem.

This is also yet another new feature on top of a great deal of others - and I'm not convinced this branch will be releasable as a production key any time soon given the vast number of new features and testing required.
