### ISSUE TITLE
MenuHandler running low on memory

### ISSUE THREAD

**Issue by silkymesmeriser** [emmamei/cdkey#50]
The MenuHandler script is running dangerously short on memory I have already had to inline a whole group of functions in order to avoid repeated stack heap collisions during usage, need to look into what tasks if any can be pulled out of there and handed out to the target scripts to deal with indirectly instead.

One option might be to look into moving some of the messages that happen when things are changed and have something else send them on the basis of the link 300 messages, though doing that might need a revert of the other change where the initial configuration read was reset to a link 300 message in order to save on redundant code in the receiver scripts which were having to deal with the same information from 2 sources in two different formats which is bad practice.

That said the link 300 message does include the name of the source script so it would make sense to have the script which takes over the messaging work could check if the message came from MenuHandler and not from Start (Notecard) or from OnlineServices (Database) which would prevent the issue that would otherwise occur with llOwnerSay spam on startup.

I had been considering along the lines of creating a specialist messaging script as unfortunately the majority of the places which would make sense to move messages too are already getting pretty full if not right from compile time they do fill up with data at runtime (RLV.lsl is the big one for this with the state tracking in fact I just fixed a stack heap bug in the RLV.lsl code by making it so that AFK and collapsed which share the same restrictions anyway use the same source name thus is stored once for both with a little logic added so the restrictions are only removed when both !afk and !collapsed).

I'll work on it and try and see what gains I can make in there without having to start dealing with removing the redundancy issues which would be a fair rewrite.

**Comment by emmamei** [comment]
Traditionally, afk did not have the same restrictions as being collapsed: collapsed was more restrictive. You also have the forced animation (collapse) and no movement or chat - none of which was true for afk in the past.

**Comment by silkymesmeriser** [comment]
I thought it only allowed IM, I could alter it on local chat as well though given the intent of the AFK mode I am not certain there is necessarily any reason why one should be both AFK and chatting.

Where do you stand on the idea?

**Comment by emmamei** [comment]
I had envisioned perhaps converting "AFK" to "low power mode" and making the key reflect that. That is what it is after all. A collapse is a "no power mode" really.

**Comment by silkymesmeriser** [comment]
Ok, well in the current code this is the list of restrictions that are currently being applied to both:
        RLV = "unsharedwear=n,unsharedunwear=n,attachallthis:=n,detachallthis:=n,";
        RLV += "fly=n,sit=n,unsit=n,tplm=n,tploc=n,temprun=n,alwaysrun=n,sendchat=n,tplure=n,";
        RLV += "sittp=n,standtp=n,shownames=n,showhovertextall=n,redirchat:999=add,rediremote:999=add,";
        RLV += getAutoTPList();

So if we are going to change it which would you tend to err towards pulling off the AFK mode, or perhaps adding to the collapsed mode?

Looking at it I can think of a couple of possible options.
For AFK perhaps remove the rediremote restriction allowing short emotes could also add @emote also which pretends to be a restriction but is actually more of an exception as it is what allows long emotes even while @sendchat=n.  Perhaps cut the showhovertextall down to showhovertextworld and allow the HUD text, we could maybe consider mooting the tp restrictions down to helpless dolly type instead ie skip on the tplure=n.  shownames we would take out too.

For collapsed there are some options we could add to it like @edit=n or @rez=n or both and possibly some of the other show restrictions like showinv, showworldmap, showminimap those three in particular also have a certain psychological effect as they have the effect of greying out buttons as does edit.

In addition another factor is that collapsed currently blocks out the dolls access to the menu in particular that's significant as it blocks even dressing through the key menu, however afk mode allows menu access and the doll can still use the dress menu on themselves.  Currently that is the only present difference though so perhaps we should definitely make some other changes.

**Comment by emmamei** [comment]
I never understood the combining of AFK and collapse in the first place - just sort of happened without discussion. AFK is supposed to be a low-power mode with light restrictions appropriate to such (no TP is a perfect restriction for AFK). collapse is supposed to be power-off - with heavy restrictions except for IM - to allow calling for help (telepathy?).

**Comment by silkymesmeriser** [comment]
Well largely the code as it was when I did that turned on basically all the restrictions the key at the time actually used with the exception of @redirchat and @rediremote so it left truncated emotes on and ... was allowed in local as opposed to silence, they didn't feel as significantly different as you seem to have been hoping for.

This is a snip from branch master
llOwnerSay("@fly=n,temprun=n,alwaysrun=n,sendchat=n,tplm=n,tploc=n,tplure=n,sittp=n,standtp=n,accepttp=n,unsit=n,sit=n");

Immidiately prior to my first touching it at all to move it to RLV.lsl it was as follows
            // AFK turns everything off
            if (RLVok) {
                llOwnerSay("@temprun=n,alwaysrun=n,sendchat=n,tplure=n,sittp=n,standtp=n,unsit=n,sit=n");
                llOwnerSay("@fly=n,tplm=n,tploc=n,accepttp=rem");
            }

I took the comment that had been added a little literally also perhaps, at least in that I read it as the objective intent to disable "everything" just as collapse did.  Anyway it's a matter of subjective interpretation whether the difference between the two originally was that great or not and not really something that benefits us to argue now anyway I am in agreement that the two modes are different and that the restrictions applied should reflect that better so seems to me the more productive discussion is on exactly what to apply to which to achieve that.

**Comment by emmamei** [comment]
Looking at the restrictions, they all make sense but one - no running, no standing up, no TP, and no flying..... Not sure about no chat, but it sort of makes sense...

Hovertext can be important to show the user that they are, in fact, in AFK mode - based on the dolly's key's text... IM is central, as it is the central way to call for help, and can be seen as "telepathic" (i.e., not using muscles or other such).

emotes can be used by the dolly to show what is happening while they are in low-power mode. Not sure if "short emotes" would be useful.... how does that translate into the "real world" ?

**Comment by silkymesmeriser** [comment]
Short emotes is the default in RLV when @sendchat=n and not having an @emote=add it limits emotes to I think it's 25 chars.

**Comment by bsdlp** [comment]
Hey guys, sorry to interrupt the flow of this issue, but it looks like I was mentioned [here](https://github.com/emmamei/cdkey/issues/50#issuecomment-32125959) by accident. When users are mentioned in a GitHub issue, they are automatically subscribed to any and all updates to the thread, which involves emails about the subject. It's trivial to unsubscribe, but it is also trivial to ensure users are not notified by code snippets!

Please wrap your code snippets in ` `backticks` ` so that `@username` won't notify + subscribe folks.

Again, sorry about the noise!
