### ISSUE TITLE
Remaining time wrong in menu dialogs

### ISSUE THREAD

**Issue by emmamei** [emmamei/cdkey#53]
The time is wrong in the menu dialog, and is always one wind behind the actual time remaining.

**Comment by emmamei** [comment]
The original key did not mention the time in the dialogs at all - and this could be an unfortunate, but viable, result if the proper time can't easily be put in.

Still, it seems that this must be doable and simply.

**Comment by silkymesmeriser** [comment]
Oops I missed that you already posted this, the one I just posted does however note the solution implementation so of the two is probably the better one to keep?
