### ISSUE TITLE
Options not behaving as expected

### ISSUE THREAD

**Issue by emmamei** [emmamei/cdkey#58]
Given the change in options, there's no clear determination as to just what option settings are, and options sometimes don't appear to be set.

A message in the text (_"Buttons reflect the current setting"_) and the addition of checkboxes would go a long ways in fixing the UI difficulties here.

A verification of current option settings would be nice - perhaps for debugging purposes, perhaps in the chat interface, or in some other fashion.

**Comment by silkymesmeriser** [comment]
The wording of the options has not changed they have just been properly organized into a common menu as would be typical user expectation so this is not a sudden new issue, is another inherited problem.

Check marks are well enough recognized and understood to indicate state that we should not need to explain the meaning of check-marks, there is a reason simple icons drawing parallels to everyday life were preferred to long text in modern interfaces.

This is already scheduled for the polish phase and there are still one or more minor functional issues that could use solving before we get to that stage.  Final polish would be more the release candidate stage of the process.

**Comment by emmamei** [comment]
Testing of the RLV options seems to confirm that they work and work properly. Testing of other compound functions ("Features") should be done.

**Comment by silkymesmeriser** [comment]
I have just done a large update to the menu options etc, a basic test confirms your results still apply Mei.  I also did a run through of all the options to do a UI toggle test and ensure the buttons do indeed correctly switch state as expected this currently seems to be true for everything course still need to verify expected behaviour from the actual feature code itself.

**Comment by emmamei** [comment]
Most everything seems to be working, though #104 relates to a problem with the `Poseable` setting. Other troubles (if any) will be opened specifically.
