### ISSUE TITLE
Key Startup errors

### ISSUE THREAD

**Issue by emmamei** [emmamei/cdkey#59]
Current key shows these errors for me:

```
Could not find script 'Taker'.
WARNING: Sanity check failure developer key not found in #RLV see README.dev for more information.
```

Current Development branch keys are kept in `#RLV/Dev Keys` and outfits and types in `#RLV/Outfits`.

**Comment by silkymesmeriser** [comment]
The first looks like an asset server issue as the name is correctly spelled and correctly capitalized.  Given that it's from you Mei I am giving you the benefit of presumption in assuming that you did not manually edit the key and rename or delete the script of the name specified.

The second means your viewer answered @version but refused to reply with a valid non null path to your key within 10 seconds despite having been sent at least two distinct requests for the information, typical response times for EU or AU based users on low end connections are at least 10 times faster than that so was your network or the sim under exceptional lag?

**Comment by emmamei** [comment]
I doubt that the lag was exceptional, but can't verify that.

A second log in generated the first error but not the second.

**Comment by silkymesmeriser** [comment]
That is consistent with my initial theory and that the first issue appeared to go away when given another copy of the key also supports the indication of an asset server issue.

I'll leave this issue open for monitoring for now in case some bizare edge case might be creating this situation.

**Comment by emmamei** [comment]
Havent seen anything like this in some time... and Taker.lsl has been removed anyway.
