### ISSUE TITLE
Dress code strips but does not dress

### ISSUE THREAD

**Issue by emmamei** [emmamei/cdkey#61]
Dress code will strip off an outfit but does not recognize current: appears to have a blank `outfitsFolder` or something. Because of this, no outfit is put on.

**Comment by emmamei** [comment]
Is this resolved?

**Comment by silkymesmeriser** [comment]
Yeah the outfitsFolder setting has been reworked to use @findfolder also which offloads a lot of work we were doing in a script to the viewer which frankly should be able to scan a folder listing a whole hell of a lot faster than we can in LSL.

**Comment by emmamei** [comment]
Havent seen this bug crop up at all - seems much better.
