### ISSUE TITLE
Key worn by Sirah or Sage are consistently stopped

### ISSUE THREAD

**Issue by emmamei** [emmamei/cdkey#62]
This has happened now four times. It appears that the key stops working, and that the only script running is MenuHandler. This results in a main menu that puts its output to the normal output channel (0) instead of the private message that it should.

Last investigation suggested lost Link Messages, but is there some way this can be avoided or worked around? Resetting the key is a brute force fix, can result in a resetting of all options, changes time available, is close to a cheat, and is beyond most users more than likely.

**Comment by emmamei** [comment]
This has cropped up with the regular key now worn by Mei. The problem may be separate, but it happens consistently and even after a Reset of the keys scripts.

**Comment by silkymesmeriser** [comment]
Pretty sure this should be working now.
