### ISSUE TITLE
Wind times lag behind by one wind and respawns forever

### ISSUE THREAD

**Issue by silkymesmeriser** [emmamei/cdkey#63]
When winding a doll using the old key MenuHandler immediately respawns the wind menu using the prior time left value, to the end user this results in a first wind which apparently has no effect at all and further winds which all claim to be 30 minutes less time than they should be.  On the last wind the menu will state that the doll has more capacity when in fact this is false and even beyond that it will respawn constantly.

MenuHandler must not respawn the new wind menu of it's own accord it must wait for a trigger from Main sent about 0.25s of sleeping time after timeLeftOnKey is sent on link.  This command should never be sent it timeLeftOnKey >= keyLimit

**Comment by emmamei** [comment]
This needs to be re-examined to see if it is a current problem.

**Comment by emmamei** [comment]
This does not seem to be a problem now.
