### ISSUE TITLE
Verify bigprefix (outfitsFolder) is set properly

### ISSUE THREAD

**Issue by emmamei** [emmamei/cdkey#7]
The variable should always have the folder containing all of the outfits. For Standard Keys this is #RLV/ and for Transforming Keys it is #RLV/Outfits or #RLV/outfits. #RLV/Dressup was a possibility at one time.

The directory would have a list of folders that contain clothes combined into outfits.

**Comment by emmamei** [comment]
This seems to be working. The usual directory is #RLV/Outfits with directories underneath for Doll Types.

**Comment by silkymesmeriser** [comment]
There was a bug with this that kept coming up as a form of race condition with Transform, if transform set a type before this was locked down it would end up trying to look in #RLV/*Typename instead I modified the handling a little and believe I solved it.

**Comment by emmamei** [comment]
Seems to be working.
