### ISSUE TITLE
Changing Gem Color causes the key to flicker

### ISSUE THREAD

**Issue by emmamei** [emmamei/cdkey#74]
When choosing a custom color, the key starts to flicker between the original color and the custom color. Choosing another standard color seems to add the new color to the flickering.

For example, if `Green` is chosen - then perhaps a custom color of `#CC9999` - then the key flickers between green and the added custom color. Choosing `Blue` makes key flicker between green, the custom grey, and blue...

**Comment by silkymesmeriser** [comment]
Have we any further evidence of this or is it safe to close?

**Comment by emmamei** [comment]
Haven't seen any - may have been an SL artifact, but if so it was an odd one. Closing.
