### ISSUE TITLE
Add Controller has duplicate and strange entries

### ISSUE THREAD

**Issue by emmamei** [emmamei/cdkey#82]
On my key, the options are `raveenaRS Re`, `Silky Mesmer`, `SamStone2 Res`, `raveenaRS Re`, and `Silky Mesmer`.

Only Silky, Dark (raveena), and Sarah are present in sim. List should be: `raveenaRS Re`, and `Silky Mesmer` with no duplicates.

**Comment by emmamei** [comment]
Problem is thus: the list of avis present in range are listed, and a list of controllers added to it. The list of current controllers should not be presented, and should be subtracted from avis present in range. If only controllers are in range, then Add Controller should be considered an error or a chat interface recommended instead.

**Comment by silkymesmeriser** [comment]
This is fixed now also
