### ISSUE TITLE
Transform confirmation non-standard selections

### ISSUE THREAD

**Issue by emmamei** [emmamei/cdkey#83]
The User Interface accepted standard is `OK` and `Cancel` generally - or possibly `Yes` or `No`. Transform confirm uses `Transform` and `Dont Transfor` (short).

Recommend using the accepted standard of `OK` and `Cancel` with the question: `Do you wish to transform?`

**Comment by silkymesmeriser** [comment]
That means those buttons can't be used elsewhere in the Menu at least not before the Menu upgrades in the next release that would allow us to tie any dialog reply back to a context, are you sure that's what you want?

**Comment by emmamei** [comment]
The problem here is that the current architecture of the key means that _every_ button in _every_ dialog in the _entire_ key must be unique. This can be considered a design flaw.

Fixing this design flaw will probably require substantial changes to the key and would best be pushed to the next version of the key. "Context" then becomes embedded and defined by the dialog listener...

For the current menu, `Transform` and `No Transform` might be suitable.

**Comment by emmamei** [comment]
This was fixed. Closing.
