### ISSUE TITLE
Max wind menu suggestions

### ISSUE THREAD

**Issue by emmamei** [emmamei/cdkey#84]
Max Time menu has a repetitive `Max` designator for each button, and has times that are extreme. Recommend changing times to `60m`, `90m`, `120m`, `180m`, `240m`, `300m`, and `360m` (360 minutes is 6 hours - still rather extreme) - and without the `Max` text prefix.

**Comment by silkymesmeriser** [comment]
As this is currently the only time option in the menu this might be an option currently will look leave it open and look into it, if it can be done without context tracking support we can do it if not will defer to future.

**Comment by emmamei** [comment]
The problem is that all menu buttons must be unique at this time. The usual answer is to make it possible for each dialog to be unique and to have its own buttons and listeners.

Currently a single listener handles buttons for the entire key, which means that _every_ button in the _entire_ key must be unique in name. Thus, no simple `OK` and `Cancel` buttons for instance... and in this case, `30` `60` `90` and so on would have to be unique names.

Best answer is to make every dialog have a unique listener - but this may invite a substantial architecture change.

Given these things - `Max 30m` and buttons like it may be the best possible names for now.
