### ISSUE TITLE
Add Safeword to Key capabilities

### ISSUE THREAD

**Issue by emmamei** [emmamei/cdkey#87]
The Key wearer should have a Safeword available.

**Comment by silkymesmeriser** [comment]
This has been done, in the help and support menu under the name Factory Reset

**Comment by emmamei** [comment]
I had considered more of an actual safeword, one that would be said in local chat. I wonder if it should just clear the Controllers alone, and let the Dolly change options themselves.

I do like the `Factory Reset` idea too.

**Comment by silkymesmeriser** [comment]
Public chat is a problem listeners on `channel 0` ie `PUBLIC_CHANNEL` are notorious for their high script time consumption and are essentially about the most resource inefficient listener possible.  At this point I have to say for one single feature and one that will only be used in extreme circumstances we fall far short of the high bar for justifying adding a channel 0 listener.

It would have to have more plus sides which would mean making use of it for other features that could benefit from it, I can think of some possible ideas to propose in the future however my current thoughts on a roadmap rule those out for some time so I am thinking this issue should be moved to future development sticking with the option we have for now.

**Comment by emmamei** [comment]
Sounds good to me.

**Comment by emmamei** [comment]
This is also related to #112 - when a safeword is added, the ability to _not_ use it could be added at the same time.

**Comment by emmamei** [comment]
For now, this will not be implemented. A button could be added to the Help menu, but this is very low priority at this time.
