### ISSUE TITLE
Refactor with RLV in one script

### ISSUE THREAD

**Issue by emmamei** [emmamei/cdkey#9]
Putting all RLV into a single script is recommended practice.

**Comment by emmamei** [comment]
This is.... mostly or completely done. Right?

**Comment by silkymesmeriser** [comment]
Mostly yes, Dress.lsl for example still generates the commands locally but passes them over the link to RLV which phrases them and can track state from there.  Most of Dress.lsl issued RLV is of the =force form anyway which are oneshot.

**Comment by emmamei** [comment]
This is done.
