### ISSUE TITLE
Avatar is memory constrained

### ISSUE THREAD

**Issue by emmamei** [emmamei/cdkey#90]
Memory runs out on the debug version of Avatar.lsl.

**Comment by emmamei** [comment]
Is this fixed?

**Comment by silkymesmeriser** [comment]
Not at the moment, still not entirely sure the best way to go about it as splitting it means duplicating about half the code from what I can see as it splits a group of things that reuse code.  There has to be a better way just not seeing it at the moment and am focusing on perfecting everything in non debug mode for the release for now.

After the release this is a priority.

**Comment by emmamei** [comment]
This doesn't seem to be a problem now; this script doesn't run out of Memory any longer.
