### ISSUE TITLE
Added RLV commands in Preferences not preserved

### ISSUE THREAD

**Issue by emmamei** [emmamei/cdkey#93]
When a new key is installed, the added RLV commands (such as on collapse) are not preserved. Presumably, this means these settings are not stored in the remote database.

There may be other such; all settings should be checked to see if they are in fact stored.

**Comment by emmamei** [comment]
This may have been fixed but needs more testing.

**Comment by silkymesmeriser** [comment]
As far as I know it was always saved there was an issue that originally llParseString2List was being used on the DB reply instead of llGetSubString which resulted in the RLV command being truncated at the first = character perhaps that is the issue you are thinking of?

**Comment by emmamei** [comment]
Its possible - even likely. Havent seen troubles in a while.

**Comment by silkymesmeriser** [comment]
Alright, closing for now we can reopen if it should occur again.
