### ISSUE TITLE
Preferences card should be distributed, active, and with defaults documented

### ISSUE THREAD

**Issue by emmamei** [emmamei/cdkey#95]
Currently there is no `Preferences` notecard (instead this role is taken by `Preferences Example`).

There should be a `Preferences` notecard with all options contained and set to their default values - to document the defaults and to explain all settings contained within.

**Comment by silkymesmeriser** [comment]
Documentation in the active preferences notecard is a bad idea, while it only takes us a single frame (22.5ms) to process a line from notecard, comment blank or otherwise there is a latency of 300-500ms for every line read.  If we must put doc in there then it should be short and EOL style.

**Comment by emmamei** [comment]
If we cant comment it, then I dont think it should be included. Comments are not just a good idea, but a project is worthless without them and such a project should be summarily rejected by any developers or buyers or users that come to it.

It is unthinkable to not document code and files.

**Comment by emmamei** [comment]
Given the time penalties for reading notecards, an active notecard should use in-line comments for documentation. A full documentation set can be added separately.

**Comment by emmamei** [comment]
This is basically complete. Text is in `nc/Preferences Example`.
