### ISSUE TITLE
Many settings not in the Preferences card

### ISSUE THREAD

**Issue by emmamei** [emmamei/cdkey#96]
There are many options that should be in the `Preferences` that are not.

A current edit added these that are already supported in the processing of `Preferences`:
- `doll gender`
- `controller name`
- `blacklist`
- `blacklist name`

Some of these need explanation.

However, there are many more that are not yet contained within the `Preferences` notecard at all that should be:
- `offlineMode`
- `debugLevel`
- `lowScriptMode` (maybe?)
- `nameOverride` (whatever this is)
- `dollyName`
- Take over allowed?
- Gem Color
- Silent Pose?

and more - quite possibly, anything that is stored in the offsite database should be settable in the local `Preferences` notecard as well.

**Comment by emmamei** [comment]
`lowScript` is an internal setting.

`debugLevel` is only valid for developer keys...

`offlineMode` has to be read and activated long before the `Preferences` file is read.

**Comment by emmamei** [comment]
`nameOverride` was part of a test and has been removed.
"Take over allowed" was revamped and is not appropriate...

**Comment by emmamei** [comment]
Every (logical) setting available to a person should be settable in the key should be added to the `Preferences` file. The file not only serves as a file of preferences, but also documentation.

In the context of this discussion, that includes things like:
- Gem Color
- Silent Pose
- Outfits Folder (if implemented)

and more.

**Comment by emmamei** [comment]
More preferences to consider for the Preferences notecard:
- wear lock expire (is this settable? should it be?)
- can AFK
- can be Dressed
- can be Wound Repetitively
- can be Carried

**Comment by silkymesmeriser** [comment]
wearLockExpire is an internal counter so no go, same applies to it's cousins poseExpire and winderRecharge etc.

**Comment by silkymesmeriser** [comment]
Consider poseable too

**Comment by emmamei** [comment]
Was thinking of those that are configurable by the user. `Poseable` is a good one.

The goal is to create a complete `Preferences` card so someone can completely configure a new Key without using the remote database. Just drop in the `Preferences` card and it'll configure the Key entirely.

**Comment by silkymesmeriser** [comment]
I tell you what, for the DB to set up the foreign key constraint I did a SELECT ... INSERT on the DB which should have revealed every possible link 300 config variable in existence let me grab the list and mark it up what every var is for and we can see where we are at then.

**Comment by emmamei** [comment]
Several of these were added to the code but not to the `Preferences Example` - which has been brought up to date with the code.
- `can wear` (self dress)
- `can pose` (poseable)
- `can afk`
- `outfits path`

`offline mode` is irrelevant with the database backend gone now.
