### ISSUE TITLE
Preferences card only support Wind Times separated by vertical bar ("|")

### ISSUE THREAD

**Issue by emmamei** [emmamei/cdkey#97]
With the recent discussion of supporting separation with a comma, this should be replicated in the `Preferences` notecard as well.

**Comment by silkymesmeriser** [comment]
This was already added in commit 049ab52, I added a line note.

**Comment by emmamei** [comment]
Line note is <a href="https://github.com/emmamei/cdkey/commit/049ab52d522710f782d14ea308d52cff40cda8bc#src-start-lslp-P91">here</a>.
