### ISSUE TITLE
Resetting of Key scripts by wearer

### ISSUE THREAD

**Issue by emmamei** [emmamei/cdkey#98]
Key currently checks RLV, and reports to the wearer how to reset the key by bypassing RLV.

Strongly recommend instead some pseudo code like this:

```
if (!isWearer) {
    addResetButton();
}
```

and pseudocode like this:

```
if (buttonPressed == "Reset Scripts") {
    if (!isWearer) {
        doReset();
    }
}
```

That is to say, no Reset button for wearer, and if they do get one somehow, it doesnt do anything.

**Comment by emmamei** [comment]
What do you think?

**Comment by silkymesmeriser** [comment]
Having it in non RLV mode is fine I don't see how the self documentation is an issue either please explain.

**Comment by emmamei** [comment]
The issue is that the Wearer can reset the Key at any time - at least that's what it looked like. With this, the Wearer cannot Reset - only others as they have access.

**Comment by silkymesmeriser** [comment]
The wearer can't reset at any time attempting to do so will cause a message

**Comment by silkymesmeriser** [comment]
Note it will work for you as you also pass isController

**Comment by emmamei** [comment]
That is true. Sarah would be the better test subject for that.. or Mara or Jane...
